#!/usr/bin/ruby -I/usr/local/acme/redist/

require 'rexml/document'
require '/etc/init.d/lib/vlan'

network = VlanSupport::Network.new "/etc/network.xml"

case ARGV[0] 
  when /start/
    network.up 
  when /stop/  
    network.down 
end

