#!/bin/bash

start() {
  cd /usr/local/acme
  export LD_LIBRARY_PATH=/usr/local/acme/native:$LD_LIBRARY_PATH
  /usr/local/bin/ruby &> /dev/null acme.rb &
  echo "$!" > /var/run/acme.pid
}

stop() {   
  if [ -f /var/run/acme.pid ] ; then
    local line p pid=
    read line < /var/run/acme.pid
    for p in $line ; do
      [ -z "${p//[0-9]/}" -a -d /proc/$p ] &&
      pid="$pid $p"
    done
    if [ -n "${pid-:}" ] ; then
      kill -9 $pid
      rm -rf /var/run/acme.pid
      return 0
    fi
  fi  
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  *)
  echo $"usage: $0 {start|stop}"
  RETVAL=1
esac
exit $RETVAL
