/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utb_sysbot_linux_LinuxProcessControl */

#ifndef _Included_utb_sysbot_linux_LinuxProcessControl
#define _Included_utb_sysbot_linux_LinuxProcessControl
#ifdef __cplusplus
extern "C" {
#endif
#undef utb_sysbot_linux_LinuxProcessControl_SIG_QUIT
#define utb_sysbot_linux_LinuxProcessControl_SIG_QUIT 3L
#undef utb_sysbot_linux_LinuxProcessControl_SIG_KILL
#define utb_sysbot_linux_LinuxProcessControl_SIG_KILL 9L
/* Inaccessible static: services */
/*
 * Class:     utb_sysbot_linux_LinuxProcessControl
 * Method:    execute
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_utb_sysbot_linux_LinuxProcessControl_execute
  (JNIEnv *, jclass, jstring);

/*
 * Class:     utb_sysbot_linux_LinuxProcessControl
 * Method:    signal
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_utb_sysbot_linux_LinuxProcessControl_signal
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
