/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cougaar_tools_utb_hardware_linux_LinuxPowerControl */

#ifndef _Included_org_cougaar_tools_utb_hardware_linux_LinuxPowerControl
#define _Included_org_cougaar_tools_utb_hardware_linux_LinuxPowerControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxPowerControl
 * Method:    powerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxPowerControl_powerOff
  (JNIEnv *, jobject);

/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxPowerControl
 * Method:    restart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxPowerControl_restart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
