/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cougaar_tools_utb_hardware_linux_LinuxNICControl */

#ifndef _Included_org_cougaar_tools_utb_hardware_linux_LinuxNICControl
#define _Included_org_cougaar_tools_utb_hardware_linux_LinuxNICControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxNICControl
 * Method:    openNic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxNICControl_openNic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxNICControl
 * Method:    closeNic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxNICControl_closeNic
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
