/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cougaar_tools_utb_hardware_linux_LinuxDriveControl */

#ifndef _Included_org_cougaar_tools_utb_hardware_linux_LinuxDriveControl
#define _Included_org_cougaar_tools_utb_hardware_linux_LinuxDriveControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxDriveControl
 * Method:    unmount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxDriveControl_unmount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxDriveControl
 * Method:    mount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxDriveControl_mount
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
