/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cougaar_tools_utb_hardware_linux_LinuxCPUControl */

#ifndef _Included_org_cougaar_tools_utb_hardware_linux_LinuxCPUControl
#define _Included_org_cougaar_tools_utb_hardware_linux_LinuxCPUControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxCPUControl
 * Method:    suckCPU
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxCPUControl_suckCPU
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cougaar_tools_utb_hardware_linux_LinuxCPUControl
 * Method:    stopSucking
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cougaar_tools_utb_hardware_linux_LinuxCPUControl_stopSucking
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
